GET http://localhost:3333/users

###

POST http://localhost:3333/users
Content-Type: application/json

{   
    "name" : "Mauricio",
    "username": "mferreiradb"
}

###

POST http://localhost:3333/todos
Content-Type: application/json

{
    "title": "teste",
    "deadline": "2023-05-01"
}